### ISSUE TITLE
14-minute Bio Film

### ISSUE THREAD

**Issue by changeseeker** [NegaMorgan/rebeccahensley.com#2]
I'd like the bio-film at https://www.youtube.com/watch?v=K7B4yEpEYCM to appear on the website under the YouTube link instead of the promo to advertise the book. Maybe it should be a different link next to the "About" link...? And the book promo should stay on there. What do you think? Thanks.

If you leave it up to me, I guess I'd have both. One called "Book" and one called "Mission." Thanks.

**Comment by NegaMorgan** [comment]
Okay, this is not that straightforward. The footer links are really for your presence on a particular website, so adding too many other links would be slightly confusing to users. I'll try something else; I disabled some other sections that I could bring back for your callout links.
